# Generated by Django 4.2.6 on 2023-10-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Module', models.CharField(max_length=255, verbose_name='nom de module')),
                ('img', models.FileField(upload_to='module_images/')),
                ('niveau', models.CharField(choices=[('M1', 'Master1'), ('M2', 'Master2')], max_length=2)),
                ('semestre', models.CharField(choices=[('S1', 'semestre1'), ('S2', 'semestre2')], max_length=2)),
                ('date_Creation', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_TP', models.CharField(max_length=255, verbose_name='titre tp')),
                ('fichier_TP', models.FileField(upload_to='tp_files/')),
                ('date_Creation', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='cupagis.module', verbose_name='nom de module')),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_Cour', models.CharField(max_length=255, verbose_name='titre cour')),
                ('fichier_Cour', models.FileField(upload_to='cour_files/')),
                ('date_Creation', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='cupagis.module', verbose_name='nom de module')),
            ],
        ),
    ]
