# Generated by Django 4.2.6 on 2023-10-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupagis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(verbose_name='sujet expose')),
                ('date_fin', models.DateTimeField(null=True)),
                ('date_Creation', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='cupagis.module', verbose_name='nom de module')),
            ],
        ),
    ]
